package com.backend.Projet.model;

public enum NotificationType {
    TASK_OFFER,
    TASK_SELECTED,
    TASK_ACCEPTED,
    TASK_REFUSED,
    ADMIN_TASK_REVIEW,
    ADMIN_WORKER_REVIEW,
    CHAT_MESSAGE,
    WORKER_VERIFIED,
    WORKER_REJECTED,
    BOOKING_REQUEST,
    BOOKING_ACCEPTED,
    BOOKING_REJECTED,
    BOOKING_COMPLETED
}
