# application-prod.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
app.storage.upload-dir=${APP_UPLOAD_DIR:uploads}
app.storage.max-upload-bytes=${APP_STORAGE_MAX_UPLOAD_BYTES:5242880}
app.sms.sender-name=${APP_SMS_SENDER:Khadamat MR}
